#!/bin/sh

[ -d /etc/config-shadow/ ] && exit 0

mkdir /etc/config-shadow/
cp /etc/config/network /etc/config-shadow/
cp /etc/config/wireless /etc/config-shadow/
cp /etc/config/system /etc/config-shadow/

. /lib/functions.sh

UCI_CONFIG_DIR=/etc/config-shadow

iface_del() {
	uci -c $UCI_CONFIG_DIR delete wireless.$1
}

config_load wireless
config_foreach iface_del wifi-iface

uci -c $UCI_CONFIG_DIR commit

hname=$(cat /sys/class/net/eth0/address | tr -d :)
uci set system.@system[-1].hostname=$hname
uci set usync.config.serial=$hname
uci set network.wan6.ifname=@wan
